# Generated by Django 5.2.1 on 2025-07-03 06:23

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dangerous_goods", "0002_dangerousgood_is_bulk_transport_allowed_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dangerousgood",
            options={
                "ordering": ["un_number"],
                "verbose_name": "Dangerous Good",
                "verbose_name_plural": "Dangerous Goods",
            },
        ),
        migrations.CreateModel(
            name="HistoricalDangerousGood",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "un_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique UN number (e.g., UN1230).",
                        max_length=10,
                        verbose_name="UN Number",
                    ),
                ),
                (
                    "proper_shipping_name",
                    models.CharField(
                        db_index=True,
                        help_text="Official name for transport.",
                        max_length=1024,
                        verbose_name="Proper Shipping Name (PSN)",
                    ),
                ),
                (
                    "simplified_name",
                    models.CharField(
                        blank=True,
                        help_text="A more concise or common name.",
                        max_length=1024,
                        null=True,
                        verbose_name="Simplified/Common Name",
                    ),
                ),
                (
                    "hazard_class",
                    models.CharField(
                        db_index=True,
                        help_text="Primary hazard class or division.",
                        max_length=20,
                        verbose_name="Hazard Class/Division",
                    ),
                ),
                (
                    "subsidiary_risks",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated subsidiary hazard classes/divisions.",
                        max_length=100,
                        null=True,
                        verbose_name="Subsidiary Risks",
                    ),
                ),
                (
                    "packing_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("I", "I (High Danger)"),
                            ("II", "II (Medium Danger)"),
                            ("III", "III (Low Danger)"),
                            ("NONE", "None / Not Applicable"),
                        ],
                        help_text="Packing group indicating danger degree.",
                        max_length=5,
                        null=True,
                        verbose_name="Packing Group",
                    ),
                ),
                (
                    "hazard_labels_required",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated required hazard labels.",
                        max_length=255,
                        null=True,
                        verbose_name="Hazard Label(s) Required",
                    ),
                ),
                (
                    "erg_guide_number",
                    models.CharField(
                        blank=True,
                        help_text="Emergency Response Guidebook number.",
                        max_length=10,
                        null=True,
                        verbose_name="ERG Guide Number",
                    ),
                ),
                (
                    "special_provisions",
                    models.TextField(
                        blank=True,
                        help_text="Applicable special provisions codes (comma-separated or text).",
                        null=True,
                        verbose_name="Special Provisions",
                    ),
                ),
                (
                    "qty_ltd_passenger_aircraft",
                    models.CharField(
                        blank=True,
                        help_text="Quantity limitation for passenger aircraft.",
                        max_length=50,
                        null=True,
                        verbose_name="Qty Ltd - Pax Aircraft",
                    ),
                ),
                (
                    "packing_instruction_passenger_aircraft",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="PI - Pax Aircraft",
                    ),
                ),
                (
                    "qty_ltd_cargo_aircraft",
                    models.CharField(
                        blank=True,
                        help_text="Quantity limitation for cargo aircraft only.",
                        max_length=50,
                        null=True,
                        verbose_name="Qty Ltd - Cargo Aircraft",
                    ),
                ),
                (
                    "packing_instruction_cargo_aircraft",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="PI - Cargo Aircraft",
                    ),
                ),
                (
                    "description_notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional descriptive notes or regulatory remarks.",
                        null=True,
                        verbose_name="Description/Notes",
                    ),
                ),
                (
                    "is_marine_pollutant",
                    models.BooleanField(default=False, verbose_name="Marine Pollutant"),
                ),
                (
                    "is_environmentally_hazardous",
                    models.BooleanField(
                        default=False, verbose_name="Environmentally Hazardous"
                    ),
                ),
                (
                    "is_fire_risk",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this substance inherently poses a significant fire risk.",
                        verbose_name="Is a Fire Risk?",
                    ),
                ),
                (
                    "is_bulk_transport_allowed",
                    models.BooleanField(
                        default=True,
                        help_text="Can this substance generally be transported in bulk quantities?",
                        verbose_name="Bulk Transport Allowed?",
                    ),
                ),
                (
                    "physical_form",
                    models.CharField(
                        choices=[
                            ("SOLID", "Solid"),
                            ("LIQUID", "Liquid"),
                            ("GAS", "Gas"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        help_text="Typical physical form (Solid, Liquid, Gas).",
                        max_length=10,
                        verbose_name="Physical Form",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Dangerous Good",
                "verbose_name_plural": "historical Dangerous Goods",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
