# Generated by Django 5.2.1 on 2025-07-13 09:04

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("vehicles", "0002_add_safety_equipment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="safetyequipmentcertification",
            new_name="vehicles_sa_equipme_3dfb6c_idx",
            old_name="vehicles_sa_equipme_1k2l3m_idx",
        ),
        migrations.RenameIndex(
            model_name="safetyequipmentcertification",
            new_name="vehicles_sa_certifi_689d6c_idx",
            old_name="vehicles_sa_certifi_2l3m4n_idx",
        ),
        migrations.RenameIndex(
            model_name="safetyequipmentcertification",
            new_name="vehicles_sa_expiry__876462_idx",
            old_name="vehicles_sa_expiry__3m4n5o_idx",
        ),
        migrations.RenameIndex(
            model_name="safetyequipmentinspection",
            new_name="vehicles_sa_equipme_3cbb72_idx",
            old_name="vehicles_sa_equipme_8h9i0j_idx",
        ),
        migrations.RenameIndex(
            model_name="safetyequipmentinspection",
            new_name="vehicles_sa_result_88fb4f_idx",
            old_name="vehicles_sa_result_9i0j1k_idx",
        ),
        migrations.RenameIndex(
            model_name="safetyequipmentinspection",
            new_name="vehicles_sa_next_in_32373d_idx",
            old_name="vehicles_sa_next_in_0j1k2l_idx",
        ),
        migrations.RenameIndex(
            model_name="safetyequipmenttype",
            new_name="vehicles_sa_categor_512071_idx",
            old_name="vehicles_sa_categor_1a2c3d_idx",
        ),
        migrations.RenameIndex(
            model_name="safetyequipmenttype",
            new_name="vehicles_sa_is_acti_4f3b56_idx",
            old_name="vehicles_sa_is_acti_2b3e4f_idx",
        ),
        migrations.RenameIndex(
            model_name="vehiclesafetyequipment",
            new_name="vehicles_ve_vehicle_791c3b_idx",
            old_name="vehicles_ve_vehicle_3c4d5e_idx",
        ),
        migrations.RenameIndex(
            model_name="vehiclesafetyequipment",
            new_name="vehicles_ve_status_39d8da_idx",
            old_name="vehicles_ve_status_4d5e6f_idx",
        ),
        migrations.RenameIndex(
            model_name="vehiclesafetyequipment",
            new_name="vehicles_ve_expiry__d8103c_idx",
            old_name="vehicles_ve_expiry__5e6f7g_idx",
        ),
        migrations.RenameIndex(
            model_name="vehiclesafetyequipment",
            new_name="vehicles_ve_next_in_d61515_idx",
            old_name="vehicles_ve_next_in_6f7g8h_idx",
        ),
        migrations.RenameIndex(
            model_name="vehiclesafetyequipment",
            new_name="vehicles_ve_serial__df0fab_idx",
            old_name="vehicles_ve_serial__7g8h9i_idx",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="capacity_volume",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="capacity_weight",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="company",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="dimensions",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="driver",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="make",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="model",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="year",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="assigned_depot",
            field=models.CharField(
                blank=True,
                help_text="Depot name (temporary)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="assigned_driver",
            field=models.ForeignKey(
                blank=True,
                help_text="Currently assigned driver",
                limit_choices_to={"role": "DRIVER"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_vehicles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="capacity_kg",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="last_known_location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                geography=True,
                help_text="Last reported GPS location of the vehicle",
                null=True,
                srid=4326,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="last_reported_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp of the last location report", null=True
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="owning_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vehicles",
                to="companies.company",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="registration_number",
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("IN_USE", "In Use"),
                    ("MAINTENANCE", "In Maintenance"),
                    ("OUT_OF_SERVICE", "Out of Service"),
                ],
                default="AVAILABLE",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("SEMI", "Semi-Trailer"),
                    ("RIGID", "Rigid Truck"),
                    ("TANKER", "Tanker"),
                    ("VAN", "Van"),
                    ("TRAILER", "Trailer"),
                    ("CONTAINER", "Container"),
                    ("OTHER", "Other"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["registration_number"], name="vehicles_ve_registr_3774f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["vehicle_type"], name="vehicles_ve_vehicle_76fbe4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(fields=["status"], name="vehicles_ve_status_f71f77_idx"),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["created_at"], name="vehicles_ve_created_3aff09_idx"
            ),
        ),
    ]
