# shipments/serializers.py
from rest_framework import serializers
from django.db import transaction
from .models import Shipment, ConsignmentItem, ShipmentStatus
from dangerous_goods.models import DangerousGood

class ConsignmentItemSerializer(serializers.ModelSerializer):
    dangerous_good_details = serializers.SerializerMethodField()
    
    class Meta:
        model = ConsignmentItem
        fields = [
            'id',
            'description',
            'quantity',
            'weight_kg',
            'length_cm',
            'width_cm',
            'height_cm',
            'is_dangerous_good',
            'dangerous_good_entry',
            'dangerous_good_details',
            'created_at',
            'updated_at',
        ]
        read_only_fields = ['id', 'created_at', 'updated_at', 'dangerous_good_details']

    def get_dangerous_good_details(self, obj):
        """Get dangerous good details if this item is a DG"""
        if obj.is_dangerous_good and obj.dangerous_good_entry:
            return {
                'un_number': obj.dangerous_good_entry.un_number,
                'proper_shipping_name': obj.dangerous_good_entry.proper_shipping_name,
                'hazard_class': obj.dangerous_good_entry.hazard_class,
                'packing_group': obj.dangerous_good_entry.packing_group,
            }
        return None

    def validate_weight_kg(self, value):
        if value is not None and value > 5000:
            raise serializers.ValidationError("Weight per item must not exceed 5000 kg.")
        if value is not None and value < 0:
            raise serializers.ValidationError("Weight must be a positive value.")
        return value
    
    def validate(self, data):
        """Object-level validation for dangerous goods fields."""
        is_dg = data.get('is_dangerous_good', getattr(self.instance, 'is_dangerous_good', False))
        
        if is_dg and not data.get('dangerous_good_entry', getattr(self.instance, 'dangerous_good_entry', None)):
            raise serializers.ValidationError({
                "dangerous_good_entry": "A Dangerous Good entry must be selected for dangerous goods."
            })
        
        return data

class ShipmentSerializer(serializers.ModelSerializer):
    items = ConsignmentItemSerializer(many=True, required=False)
    status = serializers.ChoiceField(choices=ShipmentStatus.choices, required=False)
    customer_name = serializers.SerializerMethodField()
    carrier_name = serializers.SerializerMethodField()
    freight_type_name = serializers.SerializerMethodField()
    total_items = serializers.SerializerMethodField()
    total_weight = serializers.SerializerMethodField()

    class Meta:
        model = Shipment
        fields = [
            'id',
            'tracking_number',
            'reference_number',
            'customer',
            'customer_name',
            'carrier',
            'carrier_name',
            'origin_location',
            'destination_location',
            'freight_type',
            'freight_type_name',
            'status',
            'contract_type',
            'pricing_basis',
            'dead_weight_kg',
            'volumetric_weight_m3',
            'chargeable_weight_kg',
            'estimated_pickup_date',
            'actual_pickup_date',
            'estimated_delivery_date',
            'actual_delivery_date',
            'instructions',
            'total_items',
            'total_weight',
            'created_at',
            'updated_at',
            'items',
        ]
        read_only_fields = [
            'id', 'tracking_number', 'created_at', 'updated_at',
            'customer_name', 'carrier_name', 'freight_type_name',
            'total_items', 'total_weight'
        ]

    def get_customer_name(self, obj):
        return obj.customer.name if obj.customer else None

    def get_carrier_name(self, obj):
        return obj.carrier.name if obj.carrier else None

    def get_freight_type_name(self, obj):
        return obj.freight_type.name if obj.freight_type else None

    def get_total_items(self, obj):
        return obj.items.count()

    def get_total_weight(self, obj):
        return sum(
            (item.weight_kg or 0) * item.quantity 
            for item in obj.items.all()
        )

    @transaction.atomic
    def create(self, validated_data):
        items_data = validated_data.pop('items', [])
        
        # Create shipment (tracking number auto-generated by model)
        shipment = Shipment.objects.create(**validated_data)
        
        # Create items
        for item_data in items_data:
            item_data.pop('shipment', None)  # Remove if accidentally included
            ConsignmentItem.objects.create(shipment=shipment, **item_data)
        
        return shipment

    @transaction.atomic
    def update(self, instance, validated_data):
        items_data = validated_data.pop('items', None)

        # Update shipment fields
        for attr, value in validated_data.items():
            setattr(instance, attr, value)
        instance.save()

        # Handle nested item updates
        if items_data is not None:
            # Delete existing items and recreate (simpler approach)
            # For production, consider more sophisticated matching by ID
            instance.items.all().delete()
            for item_data in items_data:
                item_data.pop('shipment', None)
                ConsignmentItem.objects.create(shipment=instance, **item_data)
        
        return instance

class ShipmentListSerializer(serializers.ModelSerializer):
    """Lightweight serializer for list views"""
    customer_name = serializers.SerializerMethodField()
    carrier_name = serializers.SerializerMethodField()
    total_items = serializers.SerializerMethodField()
    has_dangerous_goods = serializers.SerializerMethodField()

    class Meta:
        model = Shipment
        fields = [
            'id',
            'tracking_number',
            'reference_number',
            'customer_name',
            'carrier_name',
            'origin_location',
            'destination_location',
            'status',
            'total_items',
            'has_dangerous_goods',
            'estimated_pickup_date',
            'estimated_delivery_date',
            'created_at',
        ]

    def get_customer_name(self, obj):
        return obj.customer.name if obj.customer else None

    def get_carrier_name(self, obj):
        return obj.carrier.name if obj.carrier else None

    def get_total_items(self, obj):
        return obj.items.count()

    def get_has_dangerous_goods(self, obj):
        return obj.items.filter(is_dangerous_good=True).exists()
