# Generated by Django 5.2.1 on 2025-05-31 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dangerous_goods", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dangerousgood",
            name="is_bulk_transport_allowed",
            field=models.BooleanField(
                default=True,
                help_text="Can this substance generally be transported in bulk quantities?",
                verbose_name="Bulk Transport Allowed?",
            ),
        ),
        migrations.AddField(
            model_name="dangerousgood",
            name="is_fire_risk",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this substance inherently poses a significant fire risk.",
                verbose_name="Is a Fire Risk?",
            ),
        ),
        migrations.AddField(
            model_name="dangerousgood",
            name="physical_form",
            field=models.CharField(
                choices=[
                    ("SOLID", "Solid"),
                    ("LIQUID", "Liquid"),
                    ("GAS", "Gas"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                help_text="Typical physical form (Solid, Liquid, Gas).",
                max_length=10,
                verbose_name="Physical Form",
            ),
        ),
        migrations.AddField(
            model_name="segregationrule",
            name="condition_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NONE", "No Specific Condition"),
                    ("BOTH_BULK", "If Both are Bulk"),
                    ("EITHER_BULK", "If Either is Bulk"),
                    ("PRIMARY_FIRE_RISK", "If Primary Item is Fire Risk"),
                    ("SECONDARY_FIRE_RISK", "If Secondary Item is Fire Risk"),
                    (
                        "CLASS_9_LITHIUM_FIRE_RISK",
                        "If Class 9 Lithium Battery (Fire Risk)",
                    ),
                    ("AWAY_FROM_FOODSTUFFS", "Away From Foodstuffs"),
                    ("CLASS_1_LEGISLATION", "Refer to Explosives Legislation"),
                ],
                default="NONE",
                max_length=50,
                null=True,
                verbose_name="Condition Type",
            ),
        ),
        migrations.AddField(
            model_name="segregationrule",
            name="condition_value",
            field=models.CharField(
                blank=True,
                help_text="Parameter for the condition, if applicable (e.g., '3m' for separation distance).",
                max_length=255,
                null=True,
                verbose_name="Condition Value/Parameter",
            ),
        ),
        migrations.AddField(
            model_name="segregationrule",
            name="source_regulation",
            field=models.CharField(
                blank=True,
                help_text="e.g., IATA Table 9.3.A, IMDG Segregation Table, ADR Chapter X.Y, User Defined",
                max_length=100,
                null=True,
                verbose_name="Source Regulation",
            ),
        ),
        migrations.AlterField(
            model_name="dangerousgood",
            name="description_notes",
            field=models.TextField(
                blank=True,
                help_text="Additional descriptive notes or regulatory remarks.",
                null=True,
                verbose_name="Description/Notes",
            ),
        ),
        migrations.AlterField(
            model_name="dangerousgood",
            name="erg_guide_number",
            field=models.CharField(
                blank=True,
                help_text="Emergency Response Guidebook number.",
                max_length=10,
                null=True,
                verbose_name="ERG Guide Number",
            ),
        ),
        migrations.AlterField(
            model_name="dangerousgood",
            name="hazard_class",
            field=models.CharField(
                db_index=True,
                help_text="Primary hazard class or division.",
                max_length=20,
                verbose_name="Hazard Class/Division",
            ),
        ),
        migrations.AlterField(
            model_name="dangerousgood",
            name="hazard_labels_required",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated required hazard labels.",
                max_length=255,
                null=True,
                verbose_name="Hazard Label(s) Required",
            ),
        ),
        migrations.AlterField(
            model_name="dangerousgood",
            name="is_marine_pollutant",
            field=models.BooleanField(default=False, verbose_name="Marine Pollutant"),
        ),
        migrations.AlterField(
            model_name="dangerousgood",
            name="packing_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("I", "I (High Danger)"),
                    ("II", "II (Medium Danger)"),
                    ("III", "III (Low Danger)"),
                    ("NONE", "None / Not Applicable"),
                ],
                help_text="Packing group indicating danger degree.",
                max_length=5,
                null=True,
                verbose_name="Packing Group",
            ),
        ),
        migrations.AlterField(
            model_name="dangerousgood",
            name="packing_instruction_cargo_aircraft",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="PI - Cargo Aircraft"
            ),
        ),
        migrations.AlterField(
            model_name="dangerousgood",
            name="packing_instruction_passenger_aircraft",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="PI - Pax Aircraft"
            ),
        ),
        migrations.AlterField(
            model_name="dangerousgood",
            name="proper_shipping_name",
            field=models.CharField(
                db_index=True,
                help_text="Official name for transport.",
                max_length=1024,
                verbose_name="Proper Shipping Name (PSN)",
            ),
        ),
        migrations.AlterField(
            model_name="dangerousgood",
            name="qty_ltd_cargo_aircraft",
            field=models.CharField(
                blank=True,
                help_text="Quantity limitation for cargo aircraft only.",
                max_length=50,
                null=True,
                verbose_name="Qty Ltd - Cargo Aircraft",
            ),
        ),
        migrations.AlterField(
            model_name="dangerousgood",
            name="qty_ltd_passenger_aircraft",
            field=models.CharField(
                blank=True,
                help_text="Quantity limitation for passenger aircraft.",
                max_length=50,
                null=True,
                verbose_name="Qty Ltd - Pax Aircraft",
            ),
        ),
        migrations.AlterField(
            model_name="dangerousgood",
            name="simplified_name",
            field=models.CharField(
                blank=True,
                help_text="A more concise or common name.",
                max_length=1024,
                null=True,
                verbose_name="Simplified/Common Name",
            ),
        ),
        migrations.AlterField(
            model_name="dangerousgood",
            name="special_provisions",
            field=models.TextField(
                blank=True,
                help_text="Applicable special provisions codes (comma-separated or text).",
                null=True,
                verbose_name="Special Provisions",
            ),
        ),
        migrations.AlterField(
            model_name="dangerousgood",
            name="subsidiary_risks",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated subsidiary hazard classes/divisions.",
                max_length=100,
                null=True,
                verbose_name="Subsidiary Risks",
            ),
        ),
        migrations.AlterField(
            model_name="dangerousgood",
            name="un_number",
            field=models.CharField(
                db_index=True,
                help_text="Unique UN number (e.g., UN1230).",
                max_length=10,
                unique=True,
                verbose_name="UN Number",
            ),
        ),
        migrations.AlterField(
            model_name="dgproductsynonym",
            name="dangerous_good",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="synonyms",
                to="dangerous_goods.dangerousgood",
            ),
        ),
        migrations.AlterField(
            model_name="dgproductsynonym",
            name="source",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Manually Entered"),
                    ("IATA_IMPORT", "IATA Data Import"),
                    ("LEARNED_SYSTEM", "Learned by System"),
                    ("USER_CONFIRMED", "User Confirmed"),
                ],
                default="MANUAL",
                max_length=20,
                verbose_name="Source of Synonym",
            ),
        ),
        migrations.AlterField(
            model_name="dgproductsynonym",
            name="synonym",
            field=models.CharField(
                db_index=True,
                max_length=255,
                verbose_name="Keyword/Product Name/Synonym",
            ),
        ),
        migrations.AlterField(
            model_name="segregationgroup",
            name="code",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Group Code"
            ),
        ),
        migrations.AlterField(
            model_name="segregationgroup",
            name="dangerous_goods",
            field=models.ManyToManyField(
                blank=True,
                related_name="segregation_groups",
                to="dangerous_goods.dangerousgood",
            ),
        ),
        migrations.AlterField(
            model_name="segregationgroup",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Group Name"),
        ),
        migrations.AlterField(
            model_name="segregationrule",
            name="compatibility_status",
            field=models.CharField(
                choices=[
                    ("COMPATIBLE", "Compatible"),
                    ("INCOMPATIBLE_PROHIBITED", "Incompatible - Prohibited"),
                    ("CONDITIONAL_NOTES", "Conditional - See Notes"),
                    ("AWAY_FROM", "Away From"),
                    ("SEPARATED_FROM", "Separated From"),
                ],
                max_length=30,
                verbose_name="Compatibility Status",
            ),
        ),
        migrations.AlterField(
            model_name="segregationrule",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Human-readable notes, specific conditions not covered by type/value, or regulatory references.",
                null=True,
                verbose_name="Notes/Regulatory Reference",
            ),
        ),
        migrations.AlterField(
            model_name="segregationrule",
            name="primary_hazard_class",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=20,
                null=True,
                verbose_name="Primary Hazard Class",
            ),
        ),
        migrations.AlterField(
            model_name="segregationrule",
            name="rule_type",
            field=models.CharField(
                choices=[
                    ("CLASS_CLASS", "Class vs Class"),
                    ("GROUP_GROUP", "Segregation Group vs Segregation Group"),
                    ("CLASS_GROUP", "Class vs Segregation Group"),
                ],
                default="CLASS_CLASS",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="segregationrule",
            name="secondary_hazard_class",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=20,
                null=True,
                verbose_name="Secondary Hazard Class",
            ),
        ),
        migrations.AddIndex(
            model_name="dangerousgood",
            index=models.Index(
                fields=["is_fire_risk"], name="dangerous_g_is_fire_db5b8a_idx"
            ),
        ),
    ]
