# Generated by Django 5.2.1 on 2025-05-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FreightType",
            fields=[
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General Cargo"),
                            ("BULK_SOLID", "Bulk Solid"),
                            ("BULK_LIQUID", "Bulk Liquid"),
                            ("DG", "Dangerous Goods (Category)"),
                            ("LIVESTOCK", "Livestock"),
                            ("REFRIGERATED", "Refrigerated / Temperature Controlled"),
                            ("AUTOMOTIVE", "Automotive (Vehicles)"),
                            ("UGLY", "Ugly / Oversized / Out-of-Gauge Freight"),
                        ],
                        help_text="Unique code identifying the freight type.",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Freight Type Code",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Full description of the freight type.",
                        max_length=255,
                        verbose_name="Description",
                    ),
                ),
                (
                    "is_dg_category",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this freight type *itself* is the 'Dangerous Goods' category. Specific items within other types can also be DGs.",
                        verbose_name="Is Dangerous Good Category",
                    ),
                ),
                (
                    "requires_special_handling",
                    models.BooleanField(
                        default=False,
                        help_text="Does this type of freight generally require special handling procedures beyond standard?",
                        verbose_name="Requires Special Handling",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Freight Type",
                "verbose_name_plural": "Freight Types",
                "ordering": ["description"],
            },
        ),
    ]
