# Generated by Django 5.2.1 on 2025-05-31 15:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("dangerous_goods", "0002_dangerousgood_is_bulk_transport_allowed_and_more"),
        ("freight_types", "0001_initial"),
        ("locations", "0001_initial"),
        ("shipments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="consignmentitem",
            name="shipments_c_shipmen_199e49_idx",
        ),
        migrations.RemoveIndex(
            model_name="consignmentitem",
            name="shipments_c_is_dang_2835a2_idx",
        ),
        migrations.RemoveIndex(
            model_name="consignmentitem",
            name="shipments_c_un_numb_ee5f6f_idx",
        ),
        migrations.RenameIndex(
            model_name="shipment",
            new_name="shipments_s_assigne_556c74_idx",
            old_name="shipments_s_assigne_ebc2c9_idx",
        ),
        migrations.RemoveField(
            model_name="consignmentitem",
            name="hazard_class",
        ),
        migrations.RemoveField(
            model_name="consignmentitem",
            name="packing_group",
        ),
        migrations.RemoveField(
            model_name="consignmentitem",
            name="proper_shipping_name",
        ),
        migrations.RemoveField(
            model_name="consignmentitem",
            name="un_number",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="actual_arrival_date",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="actual_departure_date",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="destination_address",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="estimated_arrival_date",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="estimated_departure_date",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="origin_address",
        ),
        migrations.AddField(
            model_name="consignmentitem",
            name="dangerous_good_entry",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to the master DangerousGood entry if this item is a DG.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consignment_items",
                to="dangerous_goods.dangerousgood",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="actual_delivery_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Actual Delivery Date/Time"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="actual_pickup_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Actual Pickup Date/Time"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="carrier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carried_shipments",
                to="companies.company",
                verbose_name="Carrier",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="chargeable_weight_kg",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Chargeable Weight (kg)"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="contract_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SPOT", "Spot Rate"),
                    ("CONTRACT", "Contract Rate"),
                    ("FLAT_RATE", "Flat Rate"),
                ],
                max_length=15,
                null=True,
                verbose_name="Contract Type",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customer_shipments",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="dead_weight_kg",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Total Dead Weight (kg)"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="destination_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="terminating_shipments",
                to="locations.geolocation",
                verbose_name="Destination Location",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="estimated_delivery_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Estimated Delivery Date/Time"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="estimated_pickup_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Estimated Pickup Date/Time"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="freight_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="freight_types.freighttype",
                verbose_name="Freight Type",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="instructions",
            field=models.TextField(
                blank=True, null=True, verbose_name="Special Instructions"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="origin_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="originating_shipments",
                to="locations.geolocation",
                verbose_name="Origin Location",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="pricing_basis",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEAD_WEIGHT", "Dead Weight (kg)"),
                    ("VOLUMETRIC", "Volumetric Weight (kg)"),
                    ("PER_UNIT", "Per Handling Unit"),
                    ("FLAT_RATE", "Flat Rate per Shipment"),
                ],
                max_length=20,
                null=True,
                verbose_name="Pricing Basis",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_shipments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Requested By User",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="volumetric_weight_m3",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Total Volumetric Weight (m^3)"
            ),
        ),
        migrations.AlterField(
            model_name="consignmentitem",
            name="height_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=7,
                null=True,
                verbose_name="Height per unit (cm)",
            ),
        ),
        migrations.AlterField(
            model_name="consignmentitem",
            name="length_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=7,
                null=True,
                verbose_name="Length per unit (cm)",
            ),
        ),
        migrations.AlterField(
            model_name="consignmentitem",
            name="weight_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Weight per unit (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="consignmentitem",
            name="width_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=7,
                null=True,
                verbose_name="Width per unit (cm)",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="assigned_depot",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"location_type": "DEPOT"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="depot_managed_shipments",
                to="locations.geolocation",
                verbose_name="Assigned Depot",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="reference_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="External reference (e.g., customer PO, booking ID).",
                max_length=100,
                null=True,
                verbose_name="Reference Number",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PLANNING", "Planning"),
                    ("READY_FOR_DISPATCH", "Ready for Dispatch"),
                    ("IN_TRANSIT", "In Transit"),
                    ("AT_HUB", "At Hub/Depot"),
                    ("OUT_FOR_DELIVERY", "Out for Delivery"),
                    ("DELIVERED", "Delivered"),
                    ("EXCEPTION", "Exception/Issue"),
                    ("CANCELLED", "Cancelled"),
                    ("COMPLETED", "Completed"),
                ],
                db_index=True,
                default="PENDING",
                max_length=25,
                verbose_name="Shipment Status",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="tracking_number",
            field=models.CharField(
                db_index=True,
                editable=False,
                help_text="Unique system-generated tracking number.",
                max_length=100,
                unique=True,
                verbose_name="Tracking Number",
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["customer"], name="shipments_s_custome_4b802e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["carrier"], name="shipments_s_carrier_bf1b10_idx"
            ),
        ),
    ]
