# Generated by Django 5.2.1 on 2025-07-13 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
        ("sds", "0002_enhanced_sds_models"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AustralianGovernmentSDSSync",
        ),
        migrations.RemoveField(
            model_name="safetydatasheet",
            name="imported_from",
        ),
        migrations.RemoveField(
            model_name="sdsdatasource",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="safetydatasheet",
            name="primary_source",
        ),
        migrations.RemoveField(
            model_name="sdsqualitycheck",
            name="performed_by",
        ),
        migrations.RemoveField(
            model_name="sdsqualitycheck",
            name="sds",
        ),
        migrations.RemoveField(
            model_name="safetydatasheet",
            name="adg_classification_verified",
        ),
        migrations.RemoveField(
            model_name="safetydatasheet",
            name="australian_regulatory_status",
        ),
        migrations.RemoveField(
            model_name="safetydatasheet",
            name="confidence_score",
        ),
        migrations.RemoveField(
            model_name="safetydatasheet",
            name="data_accuracy_score",
        ),
        migrations.RemoveField(
            model_name="safetydatasheet",
            name="data_completeness_score",
        ),
        migrations.RemoveField(
            model_name="safetydatasheet",
            name="duplicate_of",
        ),
        migrations.RemoveField(
            model_name="safetydatasheet",
            name="last_source_update",
        ),
        migrations.RemoveField(
            model_name="safetydatasheet",
            name="similarity_hash",
        ),
        migrations.RemoveField(
            model_name="safetydatasheet",
            name="source_update_frequency",
        ),
        migrations.RemoveField(
            model_name="safetydatasheet",
            name="verification_status",
        ),
        migrations.RemoveField(
            model_name="safetydatasheet",
            name="verified_at",
        ),
        migrations.RemoveField(
            model_name="safetydatasheet",
            name="verified_by",
        ),
        migrations.AddField(
            model_name="safetydatasheet",
            name="document",
            field=models.ForeignKey(
                blank=True,
                help_text="The actual SDS PDF document",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sds_record",
                to="documents.document",
                verbose_name="SDS Document",
            ),
        ),
        migrations.DeleteModel(
            name="SDSDataImport",
        ),
        migrations.DeleteModel(
            name="SDSDataSource",
        ),
        migrations.DeleteModel(
            name="SDSQualityCheck",
        ),
    ]
