# Generated by Django 5.2.1 on 2025-07-14 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("load_plans", "0001_initial"),
        ("locations", "0002_alter_geolocation_options_and_more"),
        ("routes", "0001_initial"),
        ("shipments", "0002_consignmentitem_dg_quantity_type_and_more"),
        (
            "vehicles",
            "0003_rename_vehicles_sa_equipme_1k2l3m_idx_vehicles_sa_equipme_3dfb6c_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="loadplan",
            name="route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="load_plans",
                to="routes.route",
            ),
        ),
        migrations.AddField(
            model_name="loadplan",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="load_plans",
                to="vehicles.vehicle",
            ),
        ),
        migrations.AddField(
            model_name="loadingconstraint",
            name="load_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="constraints",
                to="load_plans.loadplan",
            ),
        ),
        migrations.AddField(
            model_name="loadplanitem",
            name="consignment_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="load_plan_items",
                to="shipments.consignmentitem",
            ),
        ),
        migrations.AddField(
            model_name="loadplanitem",
            name="delivery_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_items",
                to="locations.geolocation",
            ),
        ),
        migrations.AddField(
            model_name="loadplanitem",
            name="load_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="load_plans.loadplan",
            ),
        ),
        migrations.AddIndex(
            model_name="loadplan",
            index=models.Index(
                fields=["status", "created_at"], name="load_plans__status_ec73a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loadplan",
            index=models.Index(
                fields=["vehicle", "status"], name="load_plans__vehicle_babdfc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loadplan",
            index=models.Index(
                fields=["optimization_type"], name="load_plans__optimiz_90218a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loadplanitem",
            index=models.Index(
                fields=["load_plan", "load_sequence"],
                name="load_plans__load_pl_684bd5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="loadplanitem",
            index=models.Index(fields=["status"], name="load_plans__status_4d93a5_idx"),
        ),
        migrations.AddIndex(
            model_name="loadplanitem",
            index=models.Index(
                fields=["delivery_stop_number"], name="load_plans__deliver_cf1f29_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="loadplanitem",
            unique_together={
                ("load_plan", "consignment_item"),
                ("load_plan", "load_sequence"),
            },
        ),
    ]
