# Generated by Django 5.2.1 on 2025-07-14 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="geolocation",
            options={"ordering": ["name"]},
        ),
        migrations.AlterUniqueTogether(
            name="geolocation",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="geolocation",
            name="address",
            field=models.TextField(default="Unknown Address"),
        ),
        migrations.AddField(
            model_name="geolocation",
            name="city",
            field=models.CharField(default="Unknown City", max_length=100),
        ),
        migrations.AddField(
            model_name="geolocation",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="geolocation",
            name="demurrage_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether demurrage tracking is enabled for this location",
            ),
        ),
        migrations.AddField(
            model_name="geolocation",
            name="demurrage_rate_per_hour",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Hourly demurrage rate in the default currency",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="geolocation",
            name="free_time_hours",
            field=models.PositiveIntegerField(
                default=24,
                help_text="Number of free hours before demurrage charges apply",
            ),
        ),
        migrations.AddField(
            model_name="geolocation",
            name="geofence",
            field=models.JSONField(
                blank=True,
                help_text="GeoJSON polygon defining the location boundary",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="geolocation",
            name="postal_code",
            field=models.CharField(default="00000", max_length=20),
        ),
        migrations.AddField(
            model_name="geolocation",
            name="state",
            field=models.CharField(default="Unknown State", max_length=100),
        ),
        migrations.AlterField(
            model_name="geolocation",
            name="country",
            field=models.CharField(default="Unknown Country", max_length=100),
        ),
        migrations.AlterField(
            model_name="geolocation",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="Latitude coordinate",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="geolocation",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("CUSTOMER_SITE", "Customer Site"),
                    ("DEPOT", "Depot"),
                    ("WAREHOUSE", "Warehouse"),
                    ("PORT", "Port"),
                    ("AIRPORT", "Airport"),
                    ("CUSTOMS", "Customs Facility"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="geolocation",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="Longitude coordinate",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="geolocation",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name="geolocation",
            index=models.Index(
                fields=["location_type"], name="locations_g_locatio_bd6dba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="geolocation",
            index=models.Index(
                fields=["country", "city"], name="locations_g_country_b44fe5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="geolocation",
            index=models.Index(
                fields=["is_active"], name="locations_g_is_acti_2ccb4f_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="geolocation",
            name="address_structured",
        ),
        migrations.RemoveField(
            model_name="geolocation",
            name="operational_regions",
        ),
        migrations.RemoveField(
            model_name="geolocation",
            name="safe_fill_limits",
        ),
    ]
