# Generated by Django 5.2.1 on 2025-07-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HandlingUnitType',
            fields=[
                ('code', models.CharField(choices=[('PALLET', 'Pallet'), ('IBC', 'Intermediate Bulk Container (IBC)'), ('ISO_20FT', 'ISO Container 20ft'), ('ISO_40FT', 'ISO Container 40ft'), ('DRUM', 'Drum'), ('FLEXITANK', 'Flexitank'), ('BOX', 'Box/Carton'), ('BAG', 'Bag'), ('CYLINDER', 'Cylinder'), ('CUSTOM', 'Custom/Other')], help_text='Unique code identifying the handling unit type.', max_length=50, primary_key=True, serialize=False, verbose_name='Handling Unit Type Code')),
                ('description', models.CharField(help_text='Full description of the handling unit type.', max_length=255, verbose_name='Description')),
                ('nominal_volume_liters', models.FloatField(blank=True, help_text='Typical internal volume of the empty handling unit in liters, if applicable.', null=True, verbose_name='Nominal Volume (Liters)')),
                ('nominal_weight_kg', models.FloatField(blank=True, help_text='Typical weight of the empty handling unit in kilograms (tare weight).', null=True, verbose_name='Nominal Tare Weight (kg)')),
                ('is_stackable', models.BooleanField(default=False, help_text='Can this type of handling unit typically be stacked when loaded?', verbose_name='Is Stackable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Handling Unit Type',
                'verbose_name_plural': 'Handling Unit Types',
                'ordering': ['description'],
            },
        ),
    ]
