# Generated by Django 5.2.1 on 2025-07-13 22:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shipments", "0002_consignmentitem_dg_quantity_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("DG_MANIFEST", "Dangerous Goods Manifest"),
                            ("DG_DECLARATION", "Dangerous Goods Declaration"),
                            ("PACKING_LIST", "Packing List"),
                            ("COMMERCIAL_INVOICE", "Commercial Invoice"),
                            ("CUSTOMS_DECLARATION", "Customs Declaration"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="Document Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Uploaded"),
                            ("QUEUED", "Queued for Processing"),
                            ("PROCESSING", "Processing"),
                            ("VALIDATED_OK", "Validated Successfully"),
                            ("VALIDATED_WITH_ERRORS", "Validated with Errors"),
                            ("PROCESSING_FAILED", "Processing Failed"),
                        ],
                        db_index=True,
                        default="UPLOADED",
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="documents/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                ]
                            )
                        ],
                        verbose_name="File",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="Original Filename"),
                ),
                (
                    "mime_type",
                    models.CharField(max_length=100, verbose_name="MIME Type"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(verbose_name="File Size (bytes)"),
                ),
                (
                    "validation_results",
                    models.JSONField(
                        blank=True,
                        help_text="Results from document validation/processing",
                        null=True,
                        verbose_name="Validation Results",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="shipments.shipment",
                        verbose_name="Shipment",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploaded By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["document_type", "status"],
                        name="documents_d_documen_80b3b1_idx",
                    )
                ],
            },
        ),
    ]
