# Generated by Django 5.2.1 on 2025-05-31 15:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        unique=True,
                        verbose_name="Company Name",
                    ),
                ),
                (
                    "company_type",
                    models.CharField(
                        choices=[
                            ("SHIPPER", "Shipper"),
                            ("CARRIER", "Carrier"),
                            ("CUSTOMER", "Customer"),
                            ("BROKER", "Broker"),
                            ("FORWARDER", "Forwarder"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Company Type",
                    ),
                ),
                (
                    "abn",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="ABN/Tax ID",
                    ),
                ),
                (
                    "contact_info",
                    models.JSONField(
                        blank=True,
                        help_text="JSON field for various contact details like address, phone, contact persons.",
                        null=True,
                        verbose_name="Contact Information",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this company profile active?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CompanyRelationship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("CONTRACTED_TO", "Contracted To"),
                            ("WORKS_WITH", "Works With"),
                            ("OWNED_BY", "Owned By"),
                        ],
                        max_length=20,
                        verbose_name="Relationship Type",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is this business relationship currently active?",
                        verbose_name="Active Relationship",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_relationships",
                        to="companies.company",
                        verbose_name="Source Company",
                    ),
                ),
                (
                    "target_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_relationships",
                        to="companies.company",
                        verbose_name="Target Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Relationship",
                "verbose_name_plural": "Company Relationships",
                "ordering": ["source_company", "target_company"],
                "unique_together": {
                    ("source_company", "target_company", "relationship_type")
                },
            },
        ),
    ]
