# Generated by Django 5.2.1 on 2025-07-03 06:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Company Name"
                    ),
                ),
                (
                    "trading_name",
                    models.CharField(
                        blank=True,
                        help_text="Alternative name used for trading",
                        max_length=255,
                        verbose_name="Trading Name",
                    ),
                ),
                (
                    "company_type",
                    models.CharField(
                        choices=[
                            ("CUSTOMER", "Customer"),
                            ("CARRIER", "Carrier"),
                            ("SUPPLIER", "Supplier"),
                            ("WAREHOUSE", "Warehouse"),
                            ("BROKER", "Broker"),
                            ("CUSTOMS", "Customs Agent"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Company Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("SUSPENDED", "Suspended"),
                            ("PENDING", "Pending Approval"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        help_text="Company registration number (e.g., ABN, ACN)",
                        max_length=50,
                        verbose_name="Registration Number",
                    ),
                ),
                (
                    "tax_number",
                    models.CharField(
                        blank=True,
                        help_text="Tax identification number (e.g., GST, VAT)",
                        max_length=50,
                        verbose_name="Tax Number",
                    ),
                ),
                (
                    "contact_info",
                    models.JSONField(
                        default=dict,
                        help_text="\n            JSON structure containing:\n            - primary_contact: {name, email, phone, position}\n            - billing_contact: {name, email, phone, position}\n            - emergency_contact: {name, email, phone, position}\n            - addresses: [{type, street, city, state, country, postal_code}]\n            - phones: [{type, number, extension}]\n            - emails: [{type, address}]\n        ",
                        verbose_name="Contact Information",
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                (
                    "industry",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Industry"
                    ),
                ),
                (
                    "business_hours",
                    models.JSONField(
                        default=dict,
                        help_text="JSON structure for business hours by day",
                        verbose_name="Business Hours",
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Credit Limit",
                    ),
                ),
                (
                    "payment_terms_days",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Payment Terms (Days)"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=3, verbose_name="Default Currency"
                    ),
                ),
                (
                    "certifications",
                    models.JSONField(
                        default=list,
                        help_text="List of certifications and their expiry dates",
                        verbose_name="Certifications",
                    ),
                ),
                (
                    "insurance_info",
                    models.JSONField(
                        default=dict,
                        help_text="Insurance policy details and coverage",
                        verbose_name="Insurance Information",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="companies_c_name_2d8260_idx"),
                    models.Index(
                        fields=["company_type", "status"],
                        name="companies_c_company_8b70a9_idx",
                    ),
                    models.Index(
                        fields=["registration_number"],
                        name="companies_c_registr_0e3380_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CompanyRelationship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("CUSTOMER_CARRIER", "Customer-Carrier"),
                            ("PARTNER", "Partner"),
                            ("SUBSIDIARY", "Subsidiary"),
                            ("AFFILIATE", "Affiliate"),
                            ("SUPPLIER", "Supplier"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Relationship Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending Approval"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Contract Number"
                    ),
                ),
                (
                    "contract_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Contract Start Date"
                    ),
                ),
                (
                    "contract_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Contract End Date"
                    ),
                ),
                (
                    "terms",
                    models.JSONField(
                        default=dict,
                        help_text="\n            JSON structure containing:\n            - payment_terms: {days, currency, method}\n            - service_levels: {response_time, availability}\n            - special_conditions: [string]\n        ",
                        verbose_name="Terms and Conditions",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company_a",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_as_a",
                        to="companies.company",
                    ),
                ),
                (
                    "company_b",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_as_b",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Relationship",
                "verbose_name_plural": "Company Relationships",
                "indexes": [
                    models.Index(
                        fields=["relationship_type", "status"],
                        name="companies_c_relatio_3a6d96_idx",
                    ),
                    models.Index(
                        fields=["contract_start_date", "contract_end_date"],
                        name="companies_c_contrac_a7037b_idx",
                    ),
                ],
                "unique_together": {("company_a", "company_b", "relationship_type")},
            },
        ),
    ]
