# Generated by Django 5.2.1 on 2025-07-19 (manually created)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        # Add unique constraint for company registration numbers
        # Only enforce uniqueness for non-blank values since field allows blank
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(
                fields=['registration_number'],
                condition=models.Q(registration_number__gt=''),
                name='company_registration_number_unique'
            ),
        ),
        
        # Add unique constraint for tax numbers
        # Only enforce uniqueness for non-blank values since field allows blank
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(
                fields=['tax_number'],
                condition=models.Q(tax_number__gt=''),
                name='company_tax_number_unique'
            ),
        ),
        
        # Add unique constraint for contract numbers in company relationships
        # Only enforce uniqueness for non-blank values since field allows blank
        migrations.AddConstraint(
            model_name='companyrelationship',
            constraint=models.UniqueConstraint(
                fields=['contract_number'],
                condition=models.Q(contract_number__gt=''),
                name='companyrelationship_contract_number_unique'
            ),
        ),
    ]