# Generated by Django 5.2.1 on 2025-07-19 (manually created)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_add_unique_constraints'),
    ]

    operations = [
        # Strategic indexes for common query patterns
        
        # Index for industry + company type queries (business intelligence)
        migrations.AddIndex(
            model_name='company',
            index=models.Index(
                fields=['industry', 'company_type'],
                name='company_industry_type_idx'
            ),
        ),
        
        # Index for status + created date queries (reporting)
        migrations.AddIndex(
            model_name='company',
            index=models.Index(
                fields=['status', 'created_at'],
                name='company_status_created_idx'
            ),
        ),
        
        # Index for credit limit queries (financial analysis)
        migrations.AddIndex(
            model_name='company',
            index=models.Index(
                fields=['credit_limit', 'currency'],
                name='company_credit_currency_idx'
            ),
        ),
        
        # Index for payment terms queries
        migrations.AddIndex(
            model_name='company',
            index=models.Index(
                fields=['payment_terms_days', 'company_type'],
                name='company_payment_terms_type_idx'
            ),
        ),
        
        # Company relationship indexes
        
        # Index for relationship status + type queries
        migrations.AddIndex(
            model_name='companyrelationship',
            index=models.Index(
                fields=['status', 'relationship_type'],
                name='relationship_status_type_idx'
            ),
        ),
        
        # Index for contract date queries
        migrations.AddIndex(
            model_name='companyrelationship',
            index=models.Index(
                fields=['contract_start_date', 'contract_end_date', 'status'],
                name='relationship_contract_dates_idx'
            ),
        ),
        
        # Index for company A relationships (finding all relationships for a company)
        migrations.AddIndex(
            model_name='companyrelationship',
            index=models.Index(
                fields=['company_a', 'status', 'relationship_type'],
                name='relationship_company_a_status_idx'
            ),
        ),
        
        # Index for company B relationships (finding all relationships for a company)
        migrations.AddIndex(
            model_name='companyrelationship',
            index=models.Index(
                fields=['company_b', 'status', 'relationship_type'],
                name='relationship_company_b_status_idx'
            ),
        ),
    ]