# Generated by Django 5.2.1 on 2025-05-28 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(blank=True, db_index=True, help_text='External reference number for the shipment.', max_length=100, null=True)),
                ('tracking_number', models.CharField(db_index=True, editable=False, help_text='Unique system-generated tracking number.', max_length=100, unique=True)),
                ('origin_address', models.TextField(help_text='Full origin address.')),
                ('destination_address', models.TextField(help_text='Full destination address.')),
                ('assigned_depot', models.CharField(blank=True, db_index=True, help_text='Depot responsible for this shipment. (Temporary - to be FK to locations.Depot)', max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('AT_DEPOT', 'At Depot'), ('OUT_FOR_DELIVERY', 'Out for Delivery')], db_index=True, default='PENDING', help_text='Current status of the shipment.', max_length=20)),
                ('estimated_departure_date', models.DateTimeField(blank=True, null=True)),
                ('actual_departure_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_arrival_date', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tracking_number'], name='shipments_s_trackin_80db53_idx'), models.Index(fields=['status'], name='shipments_s_status_536511_idx'), models.Index(fields=['assigned_depot'], name='shipments_s_assigne_ebc2c9_idx'), models.Index(fields=['reference_number'], name='shipments_s_referen_1d106f_idx'), models.Index(fields=['created_at'], name='shipments_s_created_1bef45_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConsignmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Description of the item.')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms.', max_digits=10, null=True)),
                ('length_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Length in centimeters.', max_digits=7, null=True)),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Width in centimeters.', max_digits=7, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Height in centimeters.', max_digits=7, null=True)),
                ('is_dangerous_good', models.BooleanField(default=False, help_text='Is this item a dangerous good?')),
                ('un_number', models.CharField(blank=True, help_text='UN number for the dangerous good (e.g., UN1234).', max_length=10, null=True)),
                ('proper_shipping_name', models.CharField(blank=True, help_text='Proper shipping name for the DG.', max_length=255, null=True)),
                ('hazard_class', models.CharField(blank=True, help_text='Hazard class or division (e.g., 3, 5.1).', max_length=10, null=True)),
                ('packing_group', models.CharField(blank=True, help_text='Packing group (e.g., I, II, III).', max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipments.shipment')),
            ],
            options={
                'verbose_name': 'Consignment Item',
                'verbose_name_plural': 'Consignment Items',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['shipment'], name='shipments_c_shipmen_199e49_idx'), models.Index(fields=['is_dangerous_good'], name='shipments_c_is_dang_2835a2_idx'), models.Index(fields=['un_number'], name='shipments_c_un_numb_ee5f6f_idx')],
            },
        ),
    ]
