# Generated by Django 5.2.1 on 2025-07-13 09:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0001_initial"),
        ("vehicles", "0002_add_safety_equipment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="consignmentitem",
            name="dg_quantity_type",
            field=models.CharField(
                choices=[
                    ("STANDARD_DG", "Standard Dangerous Goods"),
                    ("LIMITED_QUANTITY", "Limited Quantity (LQ)"),
                    ("DOMESTIC_CONSUMABLE", "Domestic Consumable (DC)"),
                    ("EXCEPTED_QUANTITY", "Excepted Quantity (EQ)"),
                ],
                default="STANDARD_DG",
                help_text="Type of dangerous goods quantity classification",
                max_length=25,
                verbose_name="DG Quantity Type",
            ),
        ),
        migrations.AddField(
            model_name="consignmentitem",
            name="is_aerosol",
            field=models.BooleanField(
                default=False,
                help_text="True if this is an aerosol product (affects Class 2.1 placarding)",
                verbose_name="Is Aerosol",
            ),
        ),
        migrations.AddField(
            model_name="consignmentitem",
            name="is_fumigated_unit",
            field=models.BooleanField(
                default=False,
                help_text="True if this is UN3359 Fumigated Unit",
                verbose_name="Is Fumigated Unit",
            ),
        ),
        migrations.AddField(
            model_name="consignmentitem",
            name="receptacle_capacity_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum capacity of individual receptacle in kg",
                max_digits=10,
                null=True,
                verbose_name="Receptacle Capacity (kg)",
            ),
        ),
        migrations.AddField(
            model_name="consignmentitem",
            name="receptacle_capacity_l",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum capacity of individual receptacle in litres",
                max_digits=10,
                null=True,
                verbose_name="Receptacle Capacity (L)",
            ),
        ),
        migrations.AddField(
            model_name="consignmentitem",
            name="receptacle_type",
            field=models.CharField(
                choices=[
                    ("PACKAGE", "Package/Box"),
                    ("DRUM", "Drum"),
                    ("IBC", "Intermediate Bulk Container"),
                    ("TANK", "Tank/Portable Tank"),
                    ("CYLINDER", "Gas Cylinder"),
                    ("BAG", "Bag/Sack"),
                    ("BOTTLE", "Bottle/Container"),
                    ("OTHER", "Other"),
                ],
                default="PACKAGE",
                help_text="Type of receptacle/packaging",
                max_length=20,
                verbose_name="Receptacle Type",
            ),
        ),
        migrations.AddField(
            model_name="consignmentitem",
            name="volume_l",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Volume per unit (L)",
            ),
        ),
        migrations.AddField(
            model_name="historicalshipment",
            name="assigned_driver",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Driver assigned to transport this shipment",
                limit_choices_to={"role": "DRIVER"},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalshipment",
            name="assigned_vehicle",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Vehicle assigned to transport this shipment",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="vehicles.vehicle",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="assigned_driver",
            field=models.ForeignKey(
                blank=True,
                help_text="Driver assigned to transport this shipment",
                limit_choices_to={"role": "DRIVER"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_shipments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="assigned_vehicle",
            field=models.ForeignKey(
                blank=True,
                help_text="Vehicle assigned to transport this shipment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_shipments",
                to="vehicles.vehicle",
            ),
        ),
        migrations.AlterField(
            model_name="historicalshipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("AWAITING_VALIDATION", "Awaiting Validation"),
                    ("PLANNING", "Planning"),
                    ("READY_FOR_DISPATCH", "Ready for Dispatch"),
                    ("IN_TRANSIT", "In Transit"),
                    ("AT_HUB", "At Hub/Depot"),
                    ("OUT_FOR_DELIVERY", "Out for Delivery"),
                    ("DELIVERED", "Delivered"),
                    ("EXCEPTION", "Exception/Issue"),
                    ("CANCELLED", "Cancelled"),
                    ("COMPLETED", "Completed"),
                ],
                db_index=True,
                default="PENDING",
                max_length=25,
                verbose_name="Shipment Status",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("AWAITING_VALIDATION", "Awaiting Validation"),
                    ("PLANNING", "Planning"),
                    ("READY_FOR_DISPATCH", "Ready for Dispatch"),
                    ("IN_TRANSIT", "In Transit"),
                    ("AT_HUB", "At Hub/Depot"),
                    ("OUT_FOR_DELIVERY", "Out for Delivery"),
                    ("DELIVERED", "Delivered"),
                    ("EXCEPTION", "Exception/Issue"),
                    ("CANCELLED", "Cancelled"),
                    ("COMPLETED", "Completed"),
                ],
                db_index=True,
                default="PENDING",
                max_length=25,
                verbose_name="Shipment Status",
            ),
        ),
        migrations.CreateModel(
            name="ProofOfDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("delivered_at", models.DateTimeField(auto_now_add=True)),
                ("recipient_name", models.CharField(max_length=255)),
                ("recipient_signature_url", models.URLField(max_length=500)),
                ("delivery_notes", models.TextField(blank=True)),
                ("delivery_location", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "delivered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivered_shipments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proof_of_delivery",
                        to="shipments.shipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proof of Delivery",
                "verbose_name_plural": "Proofs of Delivery",
                "ordering": ["-delivered_at"],
            },
        ),
        migrations.CreateModel(
            name="ProofOfDeliveryPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image_url", models.URLField(max_length=500)),
                ("thumbnail_url", models.URLField(blank=True, max_length=500)),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField(blank=True, null=True)),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("taken_at", models.DateTimeField(auto_now_add=True)),
                (
                    "proof_of_delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="shipments.proofofdelivery",
                    ),
                ),
            ],
            options={
                "ordering": ["taken_at"],
            },
        ),
    ]
