# Generated by Django 5.2.1 on 2025-07-19 (manually created)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_consignmentitem_dg_quantity_type_and_more'),
    ]

    operations = [
        # Add check constraints for positive weights on Shipment model
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.CheckConstraint(
                check=models.Q(dead_weight_kg__gte=0) | models.Q(dead_weight_kg__isnull=True),
                name='shipment_dead_weight_positive'
            ),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.CheckConstraint(
                check=models.Q(volumetric_weight_m3__gte=0) | models.Q(volumetric_weight_m3__isnull=True),
                name='shipment_volumetric_weight_positive'
            ),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.CheckConstraint(
                check=models.Q(chargeable_weight_kg__gte=0) | models.Q(chargeable_weight_kg__isnull=True),
                name='shipment_chargeable_weight_positive'
            ),
        ),
        
        # Add check constraints for positive weights and volumes on ConsignmentItem model
        migrations.AddConstraint(
            model_name='consignmentitem',
            constraint=models.CheckConstraint(
                check=models.Q(weight_kg__gte=0) | models.Q(weight_kg__isnull=True),
                name='consignmentitem_weight_positive'
            ),
        ),
        migrations.AddConstraint(
            model_name='consignmentitem',
            constraint=models.CheckConstraint(
                check=models.Q(volume_l__gte=0) | models.Q(volume_l__isnull=True),
                name='consignmentitem_volume_positive'
            ),
        ),
        migrations.AddConstraint(
            model_name='consignmentitem',
            constraint=models.CheckConstraint(
                check=models.Q(receptacle_capacity_kg__gte=0) | models.Q(receptacle_capacity_kg__isnull=True),
                name='consignmentitem_receptacle_capacity_kg_positive'
            ),
        ),
        migrations.AddConstraint(
            model_name='consignmentitem',
            constraint=models.CheckConstraint(
                check=models.Q(receptacle_capacity_l__gte=0) | models.Q(receptacle_capacity_l__isnull=True),
                name='consignmentitem_receptacle_capacity_l_positive'
            ),
        ),
        
        # Add check constraints for positive dimensions
        migrations.AddConstraint(
            model_name='consignmentitem',
            constraint=models.CheckConstraint(
                check=models.Q(length_cm__gte=0) | models.Q(length_cm__isnull=True),
                name='consignmentitem_length_positive'
            ),
        ),
        migrations.AddConstraint(
            model_name='consignmentitem',
            constraint=models.CheckConstraint(
                check=models.Q(width_cm__gte=0) | models.Q(width_cm__isnull=True),
                name='consignmentitem_width_positive'
            ),
        ),
        migrations.AddConstraint(
            model_name='consignmentitem',
            constraint=models.CheckConstraint(
                check=models.Q(height_cm__gte=0) | models.Q(height_cm__isnull=True),
                name='consignmentitem_height_positive'
            ),
        ),
    ]