# Generated by Django 5.2.1 on 2025-07-19 (manually created)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_add_positive_weight_constraints'),
    ]

    operations = [
        # Add check constraints for logical date ordering on Shipment model
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.CheckConstraint(
                check=(
                    models.Q(estimated_pickup_date__isnull=True) |
                    models.Q(estimated_delivery_date__isnull=True) |
                    models.Q(estimated_pickup_date__lte=models.F('estimated_delivery_date'))
                ),
                name='shipment_estimated_pickup_before_delivery'
            ),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.CheckConstraint(
                check=(
                    models.Q(actual_pickup_date__isnull=True) |
                    models.Q(actual_delivery_date__isnull=True) |
                    models.Q(actual_pickup_date__lte=models.F('actual_delivery_date'))
                ),
                name='shipment_actual_pickup_before_delivery'
            ),
        ),
        
        # Additional logical constraint: estimated pickup should be before actual delivery if both exist
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.CheckConstraint(
                check=(
                    models.Q(estimated_pickup_date__isnull=True) |
                    models.Q(actual_delivery_date__isnull=True) |
                    models.Q(estimated_pickup_date__lte=models.F('actual_delivery_date'))
                ),
                name='shipment_estimated_pickup_before_actual_delivery'
            ),
        ),
        
        # Additional logical constraint: actual pickup should be after estimated pickup if both exist
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.CheckConstraint(
                check=(
                    models.Q(estimated_pickup_date__isnull=True) |
                    models.Q(actual_pickup_date__isnull=True) |
                    models.Q(estimated_pickup_date__lte=models.F('actual_pickup_date'))
                ),
                name='shipment_actual_pickup_after_estimated'
            ),
        ),
    ]