# Generated by Django 5.2.1 on 2025-07-19 (manually created)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_add_computed_fields'),
    ]

    operations = [
        # Composite indexes for common query patterns
        
        # Index for status + date range queries (very common for dashboards)
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(
                fields=['status', 'estimated_pickup_date'],
                name='shipment_status_pickup_date_idx'
            ),
        ),
        
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(
                fields=['status', 'estimated_delivery_date'],
                name='shipment_status_delivery_date_idx'
            ),
        ),
        
        # Index for customer + status queries (customer dashboards)
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(
                fields=['customer', 'status', 'created_at'],
                name='shipment_customer_status_created_idx'
            ),
        ),
        
        # Index for carrier + status queries (carrier dashboards)
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(
                fields=['carrier', 'status', 'created_at'],
                name='shipment_carrier_status_created_idx'
            ),
        ),
        
        # Index for driver assignment queries
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(
                fields=['assigned_driver', 'status'],
                name='shipment_driver_status_idx'
            ),
        ),
        
        # Index for vehicle assignment queries
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(
                fields=['assigned_vehicle', 'status'],
                name='shipment_vehicle_status_idx'
            ),
        ),
        
        # Index for date range queries on actual dates
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(
                fields=['actual_pickup_date', 'actual_delivery_date'],
                name='shipment_actual_dates_idx'
            ),
        ),
        
        # Consignment item indexes for dangerous goods and weight queries
        
        # Index for dangerous goods filtering
        migrations.AddIndex(
            model_name='consignmentitem',
            index=models.Index(
                fields=['is_dangerous_good', 'dangerous_good_entry'],
                name='consignmentitem_dg_idx'
            ),
        ),
        
        # Index for weight-based queries
        migrations.AddIndex(
            model_name='consignmentitem',
            index=models.Index(
                fields=['weight_kg', 'quantity'],
                name='consignmentitem_weight_qty_idx'
            ),
        ),
        
        # Index for shipment + dangerous goods queries (compliance reporting)
        migrations.AddIndex(
            model_name='consignmentitem',
            index=models.Index(
                fields=['shipment', 'is_dangerous_good', 'dg_quantity_type'],
                name='consignmentitem_shipment_dg_type_idx'
            ),
        ),
        
        # Index for receptacle capacity queries (placard calculations)
        migrations.AddIndex(
            model_name='consignmentitem',
            index=models.Index(
                fields=['receptacle_type', 'receptacle_capacity_kg'],
                name='consignmentitem_receptacle_idx'
            ),
        ),
        
        # Proof of delivery indexes
        
        # Index for delivery date queries
        migrations.AddIndex(
            model_name='proofofdelivery',
            index=models.Index(
                fields=['delivered_at', 'delivered_by'],
                name='pod_delivered_at_by_idx'
            ),
        ),
    ]