# Generated by Django 5.2.1 on 2025-07-19 (manually created)

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0006_add_strategic_indexes'),
        ('locations', '0002_alter_geolocation_options_and_more'),
    ]

    operations = [
        # Add the new ForeignKey fields for GeoLocation
        migrations.AddField(
            model_name='shipment',
            name='origin_geolocation',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='origin_shipments',
                to='locations.geolocation',
                help_text='Geographic location for shipment origin'
            ),
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination_geolocation',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='destination_shipments',
                to='locations.geolocation',
                help_text='Geographic location for shipment destination'
            ),
        ),
        
        # Add indexes for the new GeoLocation foreign keys
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(
                fields=['origin_geolocation', 'status'],
                name='shipment_origin_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(
                fields=['destination_geolocation', 'status'],
                name='shipment_destination_status_idx'
            ),
        ),
        
        # Note: We're keeping the CharField fields for backward compatibility
        # and gradual migration. In a future migration, we can:
        # 1. Migrate data from CharField to GeoLocation references
        # 2. Remove the CharField fields
        # 3. Rename the new fields to remove the '_geolocation' suffix
    ]