name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: safeshipper_test
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run black
      run: |
        black --check .

    - name: Run flake8
      run: |
        flake8 .

    - name: Run tests
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/safeshipper_test
        DJANGO_SETTINGS_MODULE: safeshipper_core.settings
        SECRET_KEY: test-key-not-used-in-production
        DEBUG: "False"
        ALLOWED_HOSTS: localhost,127.0.0.1
      run: |
        python manage.py test --keepdb 