# Generated by Django 5.2.1 on 2025-07-19 (manually created)

from django.db import migrations, models
from django.core.validators import RegexValidator


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        # Add phone number fields
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(
                max_length=20,
                blank=True,
                null=True,
                validators=[
                    RegexValidator(
                        regex=r'^\+?[\d\s\-\(\)]{7,20}$',
                        message='Phone number must be 7-20 digits and may include +, spaces, hyphens, and parentheses'
                    )
                ],
                help_text='Primary contact phone number'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(
                max_length=20,
                blank=True,
                null=True,
                validators=[
                    RegexValidator(
                        regex=r'^\+?[\d\s\-\(\)]{7,20}$',
                        message='Mobile number must be 7-20 digits and may include +, spaces, hyphens, and parentheses'
                    )
                ],
                help_text='Mobile phone number'
            ),
        ),
        
        # Add emergency contact information
        migrations.AddField(
            model_name='user',
            name='emergency_contact_name',
            field=models.CharField(
                max_length=255,
                blank=True,
                null=True,
                help_text='Name of emergency contact person'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact_phone',
            field=models.CharField(
                max_length=20,
                blank=True,
                null=True,
                validators=[
                    RegexValidator(
                        regex=r'^\+?[\d\s\-\(\)]{7,20}$',
                        message='Emergency contact phone must be 7-20 digits and may include +, spaces, hyphens, and parentheses'
                    )
                ],
                help_text='Emergency contact phone number'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact_relationship',
            field=models.CharField(
                max_length=50,
                blank=True,
                null=True,
                help_text='Relationship to emergency contact (e.g., spouse, parent, sibling)'
            ),
        ),
        
        # Add employee information
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(
                max_length=50,
                blank=True,
                null=True,
                help_text='Company employee ID or badge number'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(
                max_length=100,
                blank=True,
                null=True,
                help_text='Department or division within the company'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='position_title',
            field=models.CharField(
                max_length=100,
                blank=True,
                null=True,
                help_text='Job title or position'
            ),
        ),
        
        # Add license information (important for drivers)
        migrations.AddField(
            model_name='user',
            name='driver_license_number',
            field=models.CharField(
                max_length=50,
                blank=True,
                null=True,
                help_text='Driver license number'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='driver_license_class',
            field=models.CharField(
                max_length=10,
                blank=True,
                null=True,
                help_text='Driver license class (e.g., CDL-A, MC, HC)'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='driver_license_expiry',
            field=models.DateField(
                blank=True,
                null=True,
                help_text='Driver license expiry date'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='dangerous_goods_license',
            field=models.CharField(
                max_length=50,
                blank=True,
                null=True,
                help_text='Dangerous goods transportation license number'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='dangerous_goods_license_expiry',
            field=models.DateField(
                blank=True,
                null=True,
                help_text='Dangerous goods license expiry date'
            ),
        ),
        
        # Add profile information
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(
                blank=True,
                null=True,
                help_text='Date of birth'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(
                blank=True,
                null=True,
                help_text='Home address'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='hire_date',
            field=models.DateField(
                blank=True,
                null=True,
                help_text='Date of hire/employment start'
            ),
        ),
        
        # Add language preferences
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(
                max_length=10,
                default='en',
                choices=[
                    ('en', 'English'),
                    ('es', 'Spanish'),
                    ('fr', 'French'),
                    ('de', 'German'),
                    ('it', 'Italian'),
                    ('pt', 'Portuguese'),
                    ('zh', 'Chinese'),
                    ('ja', 'Japanese'),
                    ('ar', 'Arabic'),
                ],
                help_text='Preferred language for system interface'
            ),
        ),
        
        # Add indexes for commonly queried fields
        migrations.AddIndex(
            model_name='user',
            index=models.Index(
                fields=['employee_id'],
                name='users_user_employee_id_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(
                fields=['phone_number'],
                name='users_user_phone_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(
                fields=['department', 'role'],
                name='users_user_dept_role_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(
                fields=['driver_license_expiry'],
                name='users_user_license_expiry_idx'
            ),
        ),
    ]